from . import res_company
from . import res_country
from . import tax_type
from . import myinvois_product_classification
from . import myinvois_einvoice_type
from . import allowance_charge
from . import einvoice_payment_mode
from . import prepaid_payment
from . import payment_terms
from . import account_move
from . import res_partner
from . import scheme_agency
from . import myinvois_log
from . import myinvois_document
from . import myinvois_additional_document
from . import uom_uom
from . import res_config_settings
from . import res_partner_industry
from . import product_category
from . import account_tax
from . import myinvois_period
from . import myinvois_consolidate
from . import digital_certificate
