from odoo import fields, models

MYINVOIS_CODE_COUNTRIES = {
"ABW":"ARUBA",
"AFG":"AFGHANISTAN",
"AGO":"ANGOLA",
"AIA":"ANGUILLA",
"ALA":"ALAND ISLANDS",
"ALB":"ALBANIA",
"AND":"ANDORA",
"ARE":"UNITED ARAB EMIRATES",
"ARG":"ARGENTINA",
"ARM":"ARMENIA",
"ASM":"AMERICAN SAMOA",
"ATA":"ANTARCTICA",
"ATF":"FRENCH SOUTHERN TERRITORIES",
"ATG":"ANTIGUA AND BARBUDA",
"AUS":"AUSTRALIA",
"AUT":"AUSTRIA",
"AZE":"AZERBAIDJAN",
"BDI":"BURUNDI",
"BEL":"BELGIUM",
"BEN":"BENIN",
"BES":"BONAIRE, SINT EUSTATIUS AND SABA",
"BFA":"BURKINA FASO",
"BGD":"BANGLADESH",
"BGR":"BULGARIA",
"BHR":"BAHRAIN",
"BHS":"BAHAMAS",
"BIH":"BOSNIA AND HERZEGOVINA",
"BLM":"SAINT BARTHELEMY",
"BLR":"BELARUS",
"BLZ":"BELIZE",
"BMU":"BERMUDA",
"BOL":"BOLIVIA",
"BRA":"BRAZIL",
"BRB":"BARBADOS",
"BRN":"BRUNEI DARUSSALAM",
"BTN":"BHUTAN",
"BVT":"BOUVET ISLAND",
"BWA":"BOTSWANA",
"CAF":"CENTRAL AFRICAN REPUBLIC",
"CAN":"CANADA",
"CCK":"COCOS ISLAND",
"CHE":"SWITZERLAND",
"CHL":"CHILE",
"CHN":"CHINA",
"CIV":"COTE D’IVOIRE",
"CMR":"CAMEROON",
"COD":"CONGO, THE DEMOCRATIC REPUBLIC",
"COG":"CONGO",
"COK":"COOK ISLANDS",
"COL":"COLOMBIA",
"COM":"COMOROS",
"CPV":"CAPE VERDE",
"CRI":"COSTA RICA",
"CUB":"CUBA",
"CUW":"CURACAO",
"CXR":"CHRISTMAS ISLANDS",
"CYM":"CAYMAN ISLANDS",
"CYP":"CYPRUS",
"CZE":"CZECH REPUBLIC",
"DEU":"GERMANY",
"DJI":"DJIBOUTI",
"DMA":"DOMINICA",
"DNK":"DENMARK",
"DOM":"DOMINICAN REPUBLIC",
"DZA":"ALGERIA",
"ECU":"ECUADOR",
"EGY":"EGYPT",
"ERI":"ERITREA",
"ESH":"WESTERN SAHARA",
"ESP":"SPAIN",
"EST":"ESTONIA",
"ETH":"ETHIOPIA",
"FIN":"FINLAND",
"FJI":"FIJI",
"FLK":"FALKLAND ISLANDS (MALVINAS)",
"FRA":"FRANCE",
"FRO":"FAEROE ISLANDS",
"FSM":"MICRONESIA, FEDERATED STATES OF",
"GAB":"GABON",
"GBR":"UNITED KINGDOM",
"GEO":"GEORGIA",
"GGY":"GUERNSEY",
"GHA":"GHANA",
"GIB":"GIBRALTAR",
"GIN":"GUINEA",
"GLP":"GUADELOUPE",
"GMB":"GAMBIA",
"GNB":"GUINEA-BISSAU",
"GNQ":"EQUATORIAL GUINEA",
"GRC":"GREECE",
"GRD":"GRENADA",
"GRL":"GREENLAND",
"GTM":"GUATEMALA",
"GUF":"FRENCH GUIANA",
"GUM":"GUAM",
"GUY":"GUYANA",
"HKG":"HONG KONG",
"HMD":"HEARD AND MCDONALD ISLANDS",
"HND":"HONDURAS",
"HRV":"CROATIA",
"HTI":"HAITI",
"HUN":"HUNGARY",
"IDN":"INDONESIA",
"IMN":"ISLE OF MAN",
"IND":"INDIA",
"IOT":"BRITISH INDIAN OCEAN TERRITORY",
"IRL":"IRELAND",
"IRN":"IRAN",
"IRQ":"IRAQ",
"ISL":"ICELAND",
"ISR":"ISRAEL",
"ITA":"ITALY",
"JAM":"JAMAICA",
"JEY":"JERSEY (CHANNEL ISLANDS)",
"JOR":"JORDAN",
"JPN":"JAPAN",
"KAZ":"KAZAKHSTAN",
"KEN":"KENYA",
"KGZ":"KYRGYZSTAN",
"KHM":"CAMBODIA",
"KIR":"KIRIBATI",
"KNA":"ST.KITTS AND NEVIS",
"KOR":"THE REPUBLIC OF KOREA",
"KWT":"KUWAIT",
"LAO":"LAOS",
"LBN":"LEBANON",
"LBR":"LIBERIA",
"LBY":"LIBYAN ARAB JAMAHIRIYA",
"LCA":"SAINT LUCIA",
"LIE":"LIECHTENSTEIN",
"LKA":"SRI LANKA",
"LSO":"LESOTHO",
"LTU":"LITHUANIA",
"LUX":"LUXEMBOURG",
"LVA":"LATVIA",
"MAC":"MACAO",
"MAF":"SAINT MARTIN (FRENCH PART)",
"MAR":"MOROCCO",
"MCO":"MONACO",
"MDA":"MOLDOVA, REPUBLIC OF",
"MDG":"MADAGASCAR",
"MDV":"MALDIVES",
"MEX":"MEXICO",
"MHL":"MARSHALL ISLANDS",
"MKD":"MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF",
"MLI":"MALI",
"MLT":"MALTA",
"MMR":"MYANMAR",
"MNE":"MONTENEGRO",
"MNG":"MONGOLIA",
"MNP":"NORTHERN MARIANA ISLANDS",
"MOZ":"MOZAMBIQUE",
"MRT":"MAURITANIA",
"MSR":"MONTSERRAT",
"MTQ":"MARTINIQUE",
"MUS":"MAURITIUS",
"MWI":"MALAWI",
"MYS":"MALAYSIA",
"MYT":"MAYOTTE",
"NAM":"NAMIBIA",
"NCL":"NEW CALEDONIA",
"NER":"NIGER",
"NFK":"NORFOLK ISLAND",
"NGA":"NIGERIA",
"NIC":"NICARAGUA",
"NIU":"NIUE",
"NLD":"NETHERLANDS",
"NOR":"NORWAY",
"NPL":"NEPAL",
"NRU":"NAURU",
"NZL":"NEW ZEALAND",
"OMN":"OMAN",
"PAK":"PAKISTAN",
"PAN":"PANAMA",
"PCN":"PITCAIRN",
"PER":"PERU",
"PHL":"PHILIPPINES",
"PLW":"PALAU",
"PNG":"PAPUA NEW GUINEA",
"POL":"POLAND",
"PRI":"PUERTO RICO",
"PRK":"DEMOC.PEOPLES REP.OF KOREA",
"PRT":"PORTUGAL",
"PRY":"PARAGUAY",
"PSE":"PALESTINIAN TERRITORY, OCCUPIED",
"PYF":"FRENCH POLYNESIA",
"QAT":"QATAR",
"REU":"REUNION",
"ROU":"ROMANIA",
"RUS":"RUSSIAN FEDERATION (USSR)",
"RWA":"RWANDA",
"SAU":"SAUDI ARABIA",
"SDN":"SUDAN",
"SEN":"SENEGAL",
"SGP":"SINGAPORE",
"SGS":"SOUTH GEORGIA AND THE SOUTH SANDWICH ISLAND",
"SHN":"ST. HELENA",
"SJM":"SVALBARD AND JAN MAYEN ISLANDS",
"SLB":"SOLOMON ISLANDS",
"SLE":"SIERRA LEONE",
"SLV":"EL SALVADOR",
"SMR":"SAN MARINO",
"SOM":"SOMALIA",
"SPM":"ST. PIERRE AND MIQUELON",
"SRB":"SERBIA & MONTENEGRO",
"SSD":"SOUTH SUDAN",
"STP":"SAO TOME AND PRINCIPE",
"SUR":"SURINAME",
"SVK":"SLOVAK REPUBLIC",
"SVN":"SLOVENIA",
"SWE":"SWEDEN",
"SWZ":"ESWATINI, KINGDOM OF (SWAZILAND)",
"SXM":"SINT MAARTEN (DUTCH PART)",
"SYC":"SEYCHELLES",
"SYR":"SYRIAN ARAB REPUBLIC",
"TCA":"TURKS AND CAICOS ISLANDS",
"TCD":"CHAD",
"TGO":"TOGO",
"THA":"THAILAND",
"TJK":"TAJIKISTAN",
"TKL":"TOKELAU",
"TKM":"TURKMENISTAN",
"TLS":"TIMOR-LESTE",
"TON":"TONGA",
"TTO":"TRINIDAD AND TOBAGO",
"TUN":"TUNISIA",
"TUR":"TURKIYE",
"TUV":"TUVALU",
"TWN":"TAIWAN",
"TZA":"TANZANIA UNITED REPUBLIC",
"UGA":"UGANDA",
"UKR":"UKRAINE",
"UMI":"UNITED STATES MINOR OUTLYING ISLANDS",
"URY":"URUGUAY",
"USA":"UNITED STATES OF AMERICA",
"UZB":"UZBEKISTAN",
"VAT":"VATICAN CITY STATE (HOLY SEE)",
"VCT":"SAINT VINCENT AND GRENADINES",
"VEN":"VENEZUELA",
"VGB":"VIRGIN ISLANDS(BRITISH)",
"VIR":"VIRGIN ISLANDS(US)",
"VNM":"VIETNAM",
"VUT":"VANUATU",
"WLF":"WALLIS AND FUTUNA ISLANDS",
"WSM":"SAMOA",
"YEM":"YEMEN",
"ZAF":"SOUTH AFRICA",
"ZMB":"ZAMBIA",
"ZWE":"ZIMBABWE",
}

MYINVOIS_CODE_STATE = {
    "00" : "All States",
    "01" : "Johor",
    "02" : "Kedah",
    "03" : "Kelantan",
    "04" : "Melaka",
    "05" : "Negeri Sembilan",
    "06" : "Pahang",
    "07" : "Pulau Pinang",
    "08" : "Perak",
    "09" : "Perlis",
    "10" : "Selangor",
    "11" : "Terengganu",
    "12" : "Sabah",
    "13" : "Sarawak",
    "14" : "Wilayah Persekutuan Kuala Lumpur",
    "15" : "Wilayah Persekutuan Labuan",
    "16" : "Wilayah Persekutuan Putrajaya",
    "17" : "Not Applicable",
}
class ResCountry(models.Model):
    _inherit = 'res.country'

    code = fields.Char(
        string='Country Code', size=3,
        required=True,
        help='The ISO country code in two chars. \nYou can use this field for quick search.')
    myinvois_code = fields.Char(string="MY Invois Code")
    is_from_my_invois = fields.Boolean(string="Country Only From MY INVOIS Data")

    def transform_text(self, text):
        # Split the text into words
        words = text.split()
        # Capitalize the first letter of each word
        capitalized_words = [word.capitalize() for word in words]
        # Join the words back into a single string with spaces
        transformed_text = ' '.join(capitalized_words)
        return transformed_text

    def sync_my_invois_country(self):
        for key, value in MYINVOIS_CODE_COUNTRIES.items():
            vals = {}
            country_id = self.search([('name','ilike',value)])
            if country_id:
                # UPDATE
                country_id.write({
                    'myinvois_code' : key
                })
            else:
                # CREATE
                vals = {
                    'name':self.transform_text(value),
                    'code':key,
                    'myinvois_code':key,
                    'address_format':"%(street)s\n%(street2)s\n%(city)s\n%(state_code)s\n%(zip)s\n%(country_name)s",
                    'is_from_my_invois':True,
                }
                if vals:
                    self.create(vals)
        self.sync_state()
        return True
    
    def sync_state(self):
        state_obj = self.env['res.country.state']
        country_id = self.search([('code','=','MY')])
        if country_id:
            for key, value in MYINVOIS_CODE_STATE.items():
                state_id = state_obj.search([('name','ilike',value)])
                if state_id:
                    state_id.write({
                        'myinvois_state_code' : key
                    })
                else:
                    vals = {
                        'name':self.transform_text(value),
                        'code':key,
                        'myinvois_state_code':key,
                        'country_id':country_id.id,
                        'is_from_my_invois':True,
                    }
                    if vals:
                        state_obj.create(vals)
        return True
    
class CountryState(models.Model):
    _inherit = 'res.country.state'

    myinvois_state_code = fields.Char(string="MY Invois State Code")
    is_from_my_invois = fields.Boolean(string="Country Only From MY INVOIS Data")
